### ISSUE TITLE
`and` operator bug

### ISSUE THREAD

**Issue by raheelsayeed** [danthedeckie/simpleeval#137] opened 2024-02-15 22:08 UTC
`simpleeval.simple_eval('(Age_21 == True) and  (asdfasdfs == False)', names={'Age_21': 21}`

The above ends without raising exception with a `False`. Replacing `and` with `or` does raise an exception

**Comment by decorator-factory** [comment] 2024-03-11 10:18
Why should it raise an exception? This doesn't raise an exception in Python
```py
>>> Age_21 = 21
>>> (Age_21 == True) and  (asdfasdfs == False)
False
>>> 
```

**Comment by kurtmckee** [comment] 2024-06-18 23:19
@raheelsayeed This is not a bug. `Age_21 == True` evaluates to `False` and Python stops processing the expression due to [`and` short-circuiting](https://docs.python.org/3/library/stdtypes.html#boolean-operations-and-or-not) (see note 2 at that link):

> [`and`] is a short-circuit operator, so it only evaluates the second argument if the first one is true.

@danthedeckie I recommend closing this issue.

**Closed** 2024-10-04 20:46 UTC
